language: elixir
elixir:
  - 1.2.6
  - 1.3.4
  - 1.4.5
  - 1.5.0-rc.0
otp_release:
  - 18.3
  - 19.3
  - 20.0
matrix:
  exclude:
    - otp_release: 20.0
      elixir: 1.2.6
    - otp_release: 20.0
      elixir: 1.3.4
notifications:
  recipients:
    - andrew@andrewtimberlake.com
